name: Check if Expression.g4 is in sync with the Engine

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Expression.g4 from RedHatInsights/policies-engine
      run: curl -O https://raw.githubusercontent.com/RedHatInsights/policies-engine/master/api/src/main/antlr4/com/redhat/cloud/policies/api/model/condition/expression/parser/Expression.g4
    - name: Compare both files
      run: diff Expression.g4 src/utils/Expression/Expression.g4  || (echo "Expression.g4 is out of sync" && false)
